### ISSUE TITLE
Migrate docs copy styles to be more global

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1036]
Any text-heavy pages (i.e. /privacy-policy) could benefit from the copy styles in the docs CSS. I propose we move those out of docs.css and into main.css.

**Comment by danrabbit** [comment]
Maybe not into main.css because I think that these styles make less sense for our regular pages. This changes a lot of things with the assumption of full-width paragraphs. Maybe some kind of container in which those styles change. But it could just be its own CSS file as well as an override but not including the docs nav styles and the like.

**Comment by cassidyjames** [comment]
I was thinking migrate the copy-specific `.docs` container styles over.

**Comment by cassidyjames** [comment]
```css
.row.docs,
.row.docs .slide {
    max-width: 800px;
}

.row.docs h2,
.row.docs h3,
.row.docs h4 {
    margin-bottom: 16px;
    margin-top: 32px;
    text-align: left;
}

.row.docs h4 {
    font-weight: 400;
}
```
