### ISSUE TITLE
Half- and third-width column styling is broken

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#332]
Right now the `.column.half` styling doesn't make any sense between 442 and 500-something pixels.

Here's what we have in main.css:
```css
@media (min-width: 444px) {
    .column+.column {
        margin-left: 24px;
    }

    .column.half {
        width: 492px;
        margin: 32px 32px 0;
        vertical-align: top;
    }

    .column.third {
        width: 328px;
        margin: 32px 32px 0;
        vertical-align: top;
    }
}
```

That doesn't work since a screen that's 445px wide then gets oddly-too-wide columns and scrolls sideways.
