### ISSUE TITLE
Stripe not getting email address [$100]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#340]
Stripe will automatically send an email receipt upon successful payment. However, it appears Stripe isn't getting an email address from our site. When viewing transactions in the Stripe dashboard, no email addresses are listed and no receipts have been sent.

**Comment by cassidyjames** [comment]
`receipt_email: null` on the charge.succeeded event details.

**Comment by lewisgoddard** [comment]
I don't get this with test keys. 
```
card:
    ...
    brand: "Visa"
    country: "US"
    cvc_check: "pass"
    exp_month: 12
    exp_year: 2015
    funding: "credit"
    id: "card_5gLvMd679EDf8E"
    last4: "4242"
    name: "goddard.lewis@gmail.com"
....
client_ip: ...
created: 1423656259
email: "goddard.lewis@gmail.com"
id: ...
livemode: false
object: "token"
type: "card"
used: false
verification_allowed: true
```
